"""Generated MEMORY.md block — human-readable render of governed memory.

``MEMORY.md`` stops being the canonical store (the governance DB + KG are). It
becomes a generated, human-readable summary of ``active`` memory items, wrapped
in sentinel markers so that anything a human writes *outside* the markers is
preserved verbatim across regenerations.

    <arbitrary human notes preserved>

    <!-- FLOWLY-GENERATED-START -->
    ...generated from active memory items + KG headline facts...
    <!-- FLOWLY-GENERATED-END -->

    <more human notes preserved>

``splice_generated_block`` is the safe writer: it replaces only the region
between the sentinels and never touches manual content.
"""

from __future__ import annotations

from typing import Iterable

from flowly.memory.governance import STATUS_ACTIVE, MemoryItem

SENTINEL_START = "<!-- FLOWLY-GENERATED-START -->"
SENTINEL_END = "<!-- FLOWLY-GENERATED-END -->"

_EDIT_WARNING = (
    "<!-- This block is generated by Flowly from active memory. "
    "Edits inside the markers are overwritten. Write notes OUTSIDE the markers. -->"
)

# Display order + headings for kinds.
_KIND_ORDER = [
    ("profile", "Profile"),
    ("preference", "Preferences"),
    ("project", "Projects"),
    ("environment", "Environment"),
    ("relationship", "Relationships"),
    ("procedure", "Procedures"),
    ("correction", "Corrections"),
    ("temporal", "Time-bound"),
    ("fact", "Facts"),
]


def render_generated_block(
    items: Iterable[MemoryItem], kg_summary: str = ""
) -> str:
    """Render active items (+ optional KG summary) into the generated block.

    Only ``active`` items are rendered. Output is deterministic (items grouped by
    kind in a fixed order, sorted by text within a group).
    """
    active = [i for i in items if i.status == STATUS_ACTIVE]
    by_kind: dict[str, list[MemoryItem]] = {}
    for it in active:
        by_kind.setdefault(it.kind, []).append(it)

    lines: list[str] = [SENTINEL_START, _EDIT_WARNING, "", "# Memory"]
    rendered_any = False
    for kind, heading in _KIND_ORDER:
        group = by_kind.get(kind)
        if not group:
            continue
        rendered_any = True
        lines.append("")
        lines.append(f"## {heading}")
        # Highest-trust first (confidence desc), text as a stable tie-break — so
        # feedback that raises/lowers confidence actually changes what surfaces.
        for it in sorted(group, key=lambda x: (-x.confidence, x.text.lower())):
            lines.append(f"- {it.text.strip()}")

    if kg_summary.strip():
        rendered_any = True
        lines.append("")
        lines.append("## Knowledge Graph")
        lines.append(kg_summary.strip())

    if not rendered_any:
        lines.append("")
        lines.append("_No active memory yet._")

    lines.append("")
    lines.append(SENTINEL_END)
    return "\n".join(lines)


def _find_region(text: str) -> tuple[int, int] | None:
    """Return (start_idx, end_idx_exclusive) of the generated region, or None.

    Valid region requires START followed by an END that appears after it.
    """
    start = text.find(SENTINEL_START)
    if start == -1:
        return None
    end = text.find(SENTINEL_END, start + len(SENTINEL_START))
    if end == -1:
        return None
    return (start, end + len(SENTINEL_END))


def splice_generated_block(existing: str, block: str) -> str:
    """Insert/replace the generated block, preserving all manual content.

    - If a valid generated region exists, replace exactly that region.
    - Otherwise, append the block to the end of the existing content (treated
      entirely as manual), separated by a blank line.
    """
    region = _find_region(existing)
    if region is None:
        if not existing.strip():
            return block + "\n"
        sep = "" if existing.endswith("\n") else "\n"
        return existing + sep + "\n" + block + "\n"
    start, end = region
    return existing[:start] + block + existing[end:]


def regenerate_memory_md(gov, memory_store, kg_summary: str = "") -> str:
    """Rebuild MEMORY.md's generated block from active governance items.

    Manual content (outside the sentinels) is preserved. ``secret`` items are
    never written into MEMORY.md (it gets injected into prompts) — defense in
    depth on top of the dreamer never auto-activating sensitive candidates.
    Returns the new full file content.
    """
    items = [
        i for i in gov.list_items(status=STATUS_ACTIVE)
        if i.privacy_level != "secret"
    ]
    block = render_generated_block(items, kg_summary=kg_summary)
    existing = memory_store.read_long_term()
    new_content = splice_generated_block(existing, block)
    memory_store.write_long_term(new_content)
    return new_content


def extract_manual_content(text: str) -> str:
    """Return only the human-authored content (generated region removed)."""
    region = _find_region(text)
    if region is None:
        return text
    start, end = region
    before = text[:start].rstrip("\n")
    after = text[end:].lstrip("\n")
    if before and after:
        return before + "\n\n" + after
    return before or after
