"""Generated MEMORY.md block — human-readable render of governed memory.

``MEMORY.md`` stops being the canonical store (the governance DB + KG are). It
becomes a generated, human-readable summary of ``active`` memory items, wrapped
in sentinel markers so that anything a human writes *outside* the markers is
preserved verbatim across regenerations.

    <arbitrary human notes preserved>

    <!-- FLOWLY-GENERATED-START -->
    ...generated from active memory items + KG headline facts...
    <!-- FLOWLY-GENERATED-END -->

    <more human notes preserved>

``splice_generated_block`` is the safe writer: it replaces only the region
between the sentinels and never touches manual content.
"""

from __future__ import annotations

import re
import sqlite3
from pathlib import Path
from typing import Iterable

from flowly.memory.governance import STATUS_ACTIVE, MemoryItem

SENTINEL_START = "<!-- FLOWLY-GENERATED-START -->"
SENTINEL_END = "<!-- FLOWLY-GENERATED-END -->"

_EDIT_WARNING = (
    "<!-- This block is generated by Flowly from active memory. "
    "Edits inside the markers are overwritten. Write notes OUTSIDE the markers. -->"
)

# Display order + headings for kinds.
_KIND_ORDER = [
    ("profile", "Profile"),
    ("preference", "Preferences"),
    ("project", "Projects"),
    ("environment", "Environment"),
    ("relationship", "Relationships"),
    ("procedure", "Procedures"),
    ("correction", "Corrections"),
    ("temporal", "Time-bound"),
    ("fact", "Facts"),
]


def render_generated_block(
    items: Iterable[MemoryItem], kg_summary: str = ""
) -> str:
    """Render active items (+ optional KG summary) into the generated block.

    Only ``active`` items are rendered. Output is deterministic (items grouped by
    kind in a fixed order, sorted by text within a group).
    """
    active = [i for i in items if i.status == STATUS_ACTIVE]
    by_kind: dict[str, list[MemoryItem]] = {}
    for it in active:
        by_kind.setdefault(it.kind, []).append(it)

    lines: list[str] = [SENTINEL_START, _EDIT_WARNING, "", "# Memory"]
    rendered_any = False
    for kind, heading in _KIND_ORDER:
        group = by_kind.get(kind)
        if not group:
            continue
        rendered_any = True
        lines.append("")
        lines.append(f"## {heading}")
        # Highest-trust first (confidence desc), text as a stable tie-break — so
        # feedback that raises/lowers confidence actually changes what surfaces.
        for it in sorted(group, key=lambda x: (-x.confidence, x.text.lower())):
            lines.append(f"- {it.text.strip()}")

    if kg_summary.strip():
        rendered_any = True
        lines.append("")
        lines.append("## Knowledge Graph")
        lines.append(kg_summary.strip())

    if not rendered_any:
        lines.append("")
        lines.append("_No active memory yet._")

    lines.append("")
    lines.append(SENTINEL_END)
    return "\n".join(lines)


def _find_region(text: str) -> tuple[int, int] | None:
    """Return (start_idx, end_idx_exclusive) of the generated region, or None.

    Valid region requires START followed by an END that appears after it.
    """
    start = text.find(SENTINEL_START)
    if start == -1:
        return None
    end = text.find(SENTINEL_END, start + len(SENTINEL_START))
    if end == -1:
        return None
    return (start, end + len(SENTINEL_END))


def splice_generated_block(existing: str, block: str) -> str:
    """Insert/replace the generated block, preserving all manual content.

    - If a valid generated region exists, replace exactly that region.
    - Otherwise, append the block to the end of the existing content (treated
      entirely as manual), separated by a blank line.
    """
    region = _find_region(existing)
    if region is None:
        if not existing.strip():
            return block + "\n"
        sep = "" if existing.endswith("\n") else "\n"
        return existing + sep + "\n" + block + "\n"
    start, end = region
    return existing[:start] + block + existing[end:]


def regenerate_memory_md(gov, memory_store, kg_summary: str | None = "") -> str:
    """Rebuild MEMORY.md's generated block from active governance items.

    Manual content (outside the sentinels) is preserved. ``secret`` items are
    never written into MEMORY.md (it gets injected into prompts) — defense in
    depth on top of the dreamer never auto-activating sensitive candidates.
    Returns the new full file content.
    """
    # Serialize with the owner editor so regeneration cannot erase manual edits.
    from flowly.config.transaction import config_write_lock
    from flowly.memory.editor import atomic_write
    with config_write_lock(memory_store.memory_file):
        existing = memory_store.read_long_term()
        # An editor of governed text does not own the graph. Preserve its
        # existing summary unless the caller supplies a freshly computed one.
        if kg_summary is None:
            region = _find_region(existing)
            generated = existing[region[0]:region[1]] if region else ""
            heading = "\n## Knowledge Graph\n"
            kg_summary = generated.split(heading, 1)[1].split(SENTINEL_END, 1)[0].strip() if heading in generated else ""
        items = [
            i for i in gov.list_items(status=STATUS_ACTIVE)
            if i.privacy_level != "secret"
        ]
        items = without_noted(items, extract_manual_content(existing))
        block = render_generated_block(items, kg_summary=kg_summary)
        new_content = splice_generated_block(existing, block)
        atomic_write(memory_store.memory_file, new_content)
    return new_content


def extract_manual_content(text: str) -> str:
    """Return only the human-authored content (generated region removed)."""
    region = _find_region(text)
    if region is None:
        return text
    start, end = region
    before = text[:start].rstrip("\n")
    after = text[end:].lstrip("\n")
    if before and after:
        return before + "\n\n" + after
    return before or after


# ── One statement per note ────────────────────────────────────────────────
#
# memory_append writes the note into MEMORY.md (outside the generated block,
# stamped ``<!-- YYYY-MM-DD HH:MM -->``) and governance records it as an item
# the block renders, so every note reached the prompt twice. Governance stays
# the record; the prompt states each note once, and a note the owner or the
# agent retired is not stated at all.

_NOTE_STAMP = re.compile(r"^\s*<!--\s*\d{4}-\d{2}-\d{2} \d{2}:\d{2}\s*-->\s*$", re.M)


def fold(text: str) -> str:
    """Whitespace- and case-insensitive form used to compare memory text."""
    return " ".join(text.split()).casefold()


def paragraphs(text: str) -> list[str]:
    return [chunk.strip() for chunk in re.split(r"\n\s*\n", text) if chunk.strip()]


def note_body(paragraph: str) -> str:
    """A note's words, without memory_append's timestamp comment."""
    return _NOTE_STAMP.sub("", paragraph).strip()


def noted_texts(manual: str) -> set[str]:
    """Each note written outside the generated block, folded: every stamped
    note whole, and every paragraph."""
    units: set[str] = set()
    for note in _NOTE_STAMP.split(manual):
        if note.strip():
            units.add(fold(note))
        units.update(fold(note_body(chunk)) for chunk in paragraphs(note))
    units.discard("")
    return units


def without_noted(items: Iterable[MemoryItem], manual: str) -> list[MemoryItem]:
    """Leave out of the generated block the governed copy of a note MEMORY.md
    already states (the prompt reads the whole file). The copy returns if the
    note is removed from the file."""
    noted = noted_texts(manual)
    return [i for i in items if not (i.ref_kind == "memory_md" and fold(i.text) in noted)]


def governance_states(path: Path) -> list[tuple[str, str]] | None:
    """(status, text) of every governed item, read-only; None when the index
    cannot be read."""
    if not path.exists():
        return []
    try:
        connection = sqlite3.connect(f"{path.as_uri()}?mode=ro", uri=True, timeout=0.25)
        try:
            return [(str(row[0]), str(row[1] or "")) for row in
                    connection.execute("SELECT status, text FROM memory_items LIMIT 10001")]
        finally:
            connection.close()
    except sqlite3.Error:
        return None


def withhold_retired_notes(memory_md: str, states: list[tuple[str, str]]) -> str:
    """MEMORY.md as the agent's prompt may state it: a note outside the
    generated block that carries an item which is no longer active memory
    (rejected, superseded, stale, or waiting for review) is left out, as a
    call's memory already leaves it out. Text an active item also has stays.
    The generated block is kept as it is (it renders active items only)."""
    active = {fold(text) for status, text in states if status == STATUS_ACTIVE}
    retired = {fold(text) for status, text in states if status != STATUS_ACTIVE} - active
    retired.discard("")
    if not retired:
        return memory_md
    # A sentence-length item is withheld wherever its words appear; a short
    # one only as a whole note, so a retired "Codex" cannot hide every note
    # that mentions Codex.
    long_texts = [text for text in retired if len(text) >= 24]

    def retired_note(chunk: str) -> bool:
        body = fold(note_body(chunk))
        return body in retired or any(text in body for text in long_texts)

    def keep(part: str) -> str:
        return "\n\n".join(chunk for chunk in paragraphs(part) if not retired_note(chunk))

    region = _find_region(memory_md)
    if region is None:
        return keep(memory_md)
    start, end = region
    before, after = keep(memory_md[:start]), keep(memory_md[end:])
    return "\n\n".join(part for part in (before, memory_md[start:end], after) if part)
